config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/conversations/count', to: "conversations#count"
  post '/sendgrid-event', to: proc { [200, {}, ['']] }
  get '/users/confirm', to: "users#confirm"

  resources :users, only: [:show, :update]
  resources :conversations
  resources :replacements

  mount_griddler

  root 'pages#home'

  end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :conversations
  has_many :replacements

  validates_presence_of :looper_name
  validates_uniqueness_of :looper_name

  before_validation :add_looper_name, if: Proc.new { |user| user.looper_name.blank? }
  before_create :add_looper_title, if: Proc.new { |user| user.looper_title.blank? }
  before_create :set_default_privacy

  validates :privacy, inclusion: { in: ["private", "public"] }, if: :privacy

  # instance methods

  def looper_email
    "#{self.looper_name}@mlooper.com"
  end

  def full_looper_name
    "#{self.looper_name.capitalize} Turing"
  end

  # activerecord callbacks

  def add_looper_name
    self.looper_name = Faker::Name.first_name.downcase
  end

  def add_looper_title
    self.looper_title = Faker::Name.title
  end

  def set_default_privacy
    if !self.privacy
      self.privacy = "public"
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update]
  load_and_authorize_resource :except => [:confirm]

  def show
    if @user == current_user
      @conversations = current_user.conversations
    else
      @conversations = @user.conversations.public_scope
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.js
      else
        format.js
      end
    end
  end

  def confirm
    # @user = User.last
    # @first_email = Email.first
    @user = User.confirm_by_token(params[:confirm_token])
    @reset_token = params[:reset_token]
    if @user.errors.empty?
      @first_email = @user.conversations.first.emails.last
      @first_email.update(send_at: Time.now.utc+1.hour)
      respond_to do |format|
        format.html
      end
    else
      redirect_to root_url, :alert => "Your confirmation token is invalid."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:privacy)
    end
end

app/views/users/_privacy.html.erb
<%= form_for(user, remote: true) do |f| %>
  Emails I forward to the sp@mlooper.com will be marked <b><%=user.privacy%></b>.<br />
  <%=f.hidden_field :privacy, value: user.privacy=='public' ? 'private' : 'public' %>
  <%=f.submit "Make My Emails #{user.privacy=='public' ? 'Private' : 'Public'}", class: "btn btn-xs btn-default" %>
<% end %>

app/views/users/confirm.html.erb
<h1>Thanks for confirming your account!</h1>

<p>Your first email is scheduled to be sent at <b><%=local_time(@first_email.send_at.stamp("March 3rd, 2014 10:23am")) %></b>. Here is a preview of what will be sent to the spammer:</p>

<br />
<blockquote>
  <b>To: <%=@first_email.conversation.spammers_email %></b><br /><br />
  <%=simple_format(@first_email.body_without_forwarded_text.html_safe)%>
</blockquote>

<hr />

<div class="col-sm-4 col-sm-offset-4">
  <p>If you'd like to edit the email above (i.e. remove your personal identifying information) before it goes out, then create a password below to login to your account.</p>

  <%= form_for(@user, url: password_path(@user), html: { method: :put }) do |f| %>
    <%= f.hidden_field :reset_password_token, value: @reset_token %>

    <div class="form-group">
      <%= f.label :password, "New password" %>
      <%= f.password_field :password, autofocus: true, autocomplete: "off", class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation, "Confirm new password" %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
    </div>
    <br />
    <div class="actions">
      <%= f.submit "Create My Password", class: "btn btn-primary btn-block" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<% if user_signed_in? && current_user == @user %>
  <div class="well">
    <h3>User settings</h3>
    <div id="user-privacy-toggle"><%= render partial: "privacy", locals: { user: current_user } %></div>
    <hr />

    <h3>Replacements</h3>
    When you forward an email to the sp@mlooper, you might want us to parse out sensitive words.<br/>Enter the words you want us to strip and replace it with below.
    <div id="replacements-table"><%= render partial: "/replacements/table", locals: { replacements: current_user.replacements } %></div>
  </div>
<% end %>

<h3>Conversations</h3>
To get started, forward a spammy email to sp@mlooper.com !
<%= render partial: "/conversations/table" %>

app/views/users/update.js.erb
$("#user-privacy-toggle").html("<%= raw escape_javascript(render partial: '/users/privacy', locals: { user: @user } ) %>")